### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by joaopedrosgs** [Tokeiburu/GRFEditor#4]
Hey! First of all, thank for your work, GRFEditor is an awesome software =)

I'm trying to find a way to convert all 3d models from their natives formats to gltf and I wanted to use part of your code for the purpose of parsing the files. However, it seems that nowadays Windows doesn't work really well with .Net framework 3.5 (for some reason I cant even install it). 

Do you have any guide on how to setup the build environment?

**Comment by SapitoSucio** [comment]
which window are you using ?

**Comment by joaopedrosgs** [comment]
I'm using Windows 11 22621.2428

**Comment by Tokeiburu** [comment]
Hmm, while this doesn't answer your question, I'd really recommend using another source to convert those files to gltf. I want to rewrite the code I made because it's... old and quite messy. You should check out the roBrowser project instead (it's what I used as a base anyway).

Also, .net 3.5 should work just fine with Windows 11, so I'm not sure what's happening.

**Comment by joaopedrosgs** [comment]
Ops, sorry for the delay. But I was able to use another source code as reference. Thanks!
